# Generated by Django 4.2.26 on 2025-11-19 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ['-published_date'], 'verbose_name': 'News Post', 'verbose_name_plural': 'News Posts'},
        ),
        migrations.AddField(
            model_name='newspost',
            name='category',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('academic', 'Academic'), ('research', 'Research'), ('sports', 'Sports'), ('event', 'Event'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='newspost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newspost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='excerpt',
            field=models.TextField(help_text='Short summary of the news', max_length=300),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
