# Generated by Django 4.2.26 on 2025-11-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='NORSU Santa Catalina - Bayawan Campus', max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, upload_to='settings/')),
                ('contact_email', models.EmailField(default='info@norsu-bayawan.edu.ph', max_length=254)),
                ('contact_phone', models.CharField(default='+63 XXX-XXXX-XXX', max_length=20)),
                ('address', models.TextField(default='Santa Catalina, Negros Oriental, Philippines')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
