# Generated by assistant to add id_number to UserProfile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
    ]
